[package]
name = "ktrl"
version = "0.1.0"
authors = ["Itay Garin <thifixp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"
libc = "0.2.70"
lazy_static = "1.4.0"
inner = "0.1.1"
serde = "1.0.110"
ron = "0.6.0"
clap = "2.33.1"
log = "0.4.8"
simplelog = "0.8.0"
