[package]
name = "ktrl"
version = "0.1.0"
authors = ["Itay Garin <thifixp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.17.0"
input-event-codes = "0.2.1"
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"