[package]
name = "ktrl"
version = "0.0.1"
authors = ["jtroo <j.andreitabs@gmail.com>"]
description = "Keyboard multi-layout customization"
keywords = ["cli", "linux", "windows", "keyboard", "layout"]
categories = ["command-line-utilities"]
homepage = "https://github.com/jtroo/ktrl"
repository = "https://github.com/jtroo/ktrl"
documentation = "https://github.com/jtroo/ktrl"
readme = "README.md"
license = "LGPL-3.0"
edition = "2021"

[dependencies]
libc = "0.2.70"
clap = "2.33.1"
log = "0.4.8"
simplelog = "0.8.0"
anyhow = "1"
once_cell = "1"
parking_lot = "0.12"

# Using my personal fork to derive hash on a type
keyberon = { git = "https://github.com/jtroo/keyberon", rev = "49978414bf" }

[target.'cfg(target_os = "linux")'.dependencies]
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"
nix = "0.17.0"

[target.'cfg(target_os = "windows")'.dependencies]
widestring = "1.0.0-beta.1"
winapi = { version = "0.3.9", features = ["consoleapi", "wincon"] }
encode_unicode = "0.3.6"
native-windows-gui = { version = "1.0.12", features = [
    "cursor",
    "embed-resource",
    "menu",
    "message-window",
    "no-styling",
] }
