[package]
name = "ktrl"
version = "0.1.0"
authors = ["Itay Garin <thifixp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"
libc = "0.2.70"
