[package]
name = "ktrl"
version = "0.1.8"
authors = ["Itay Garin <thifixp@gmail.com>"]
description = "A Supercharged Keyboard Programming Daemon"
keywords = ["cli", "linux", "daemon", "keyboard", "layout"]
categories = ["command-line-utilities"]
homepage = "https://github.com/ItayGarin/ktrl"
repository = "https://github.com/ItayGarin/ktrl"
documentation = "https://github.com/ItayGarin/ktrl"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"

[dependencies]
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"
libc = "0.2.70"
clap = "2.33.1"
log = "0.4.8"
simplelog = "0.8.0"
nix = "0.17.0"
anyhow = "1"
once_cell = "1"

# Using my personal fork to derive hash on a type
keyberon = { git = "https://github.com/jtroo/keyberon", rev = "49978414bf" }
